export const MOVIE_ADD = "MOVIE_ADD";
export const MOVIE_DELETE = "MOVIE_DELETE";
export const MOVIE_UPLOAD = "MOVIE_UPLOAD";
export const FETCH_TODO_SUCCESS = "FETCH_TODO_SUCCESS";
export const MOVIE_SEARCH = "MOVIE_SEARCH";
export const MOVIE_SORT_NAME = "MOVIE_SORT_NAME";
